#    / \  | | __ _  ___ _ __(_) |_| |_ _   _
#   / _ \ | |/ _` |/ __| '__| | __| __| | | |
#  / ___ \| | (_| | (__| |  | | |_| |_| |_| |
# /_/   \_\_|\__,_|\___|_|  |_|\__|\__|\__, |
# By Jerrod Havig 2024-06-06           |___/
# $HOME/.config/alacritty/alacritty.toml


[ window ]
opacity = 0.9
blur = true
padding.x = 6
padding.y = 3
decorations = "none"
decorations_theme_variant = "none"

[ font ]
size = 12.0
normal.family = "GeistMonoNerdFont"
bold.family = "GeistMonoNerdFont"
italic.family = "GeistMonoNerdFont"
bold_italic.family = "GeistMonoNerdFont"

[general]
live_config_reload = true
# Themes --
import = [
	#"~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
	#"~/.config/alacritty/themes/catppuccin-mocha.toml"
	#"~/.config/alacritty/themes/aura-theme.toml"
	#"~/.config/alacritty/themes/dracula.toml"
	"~/.config/alacritty/themes/rose-pine.toml"
]

[ env ]
TERM = "xterm-256color"

[ scrolling ]
history = 2000

[ cursor ]
unfocused_hollow = true
style = { shape = "Block", blinking = "On"}
vi_mode_style = { shape = "Block", blinking = "On"}
blink_interval = 350
thickness = 0.2
